### ISSUE TITLE
Get UnicodeDecodeError when using this plugin in windows 7

### ISSUE THREAD

**Issue by wsdjeg** [google/vimdoc#104]
when using this tool in window 7, I get:

```
C:\Users\Administrator\.SpaceVim>python -m vimdoc .
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\vimdoc\__main__.py", line 22, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\vimdoc\__main__.py", line 18, in main
    for module in Modules(args.plugin):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\vimdoc\module.py", line 421, in Modules
    lines = list(filehandle)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x96 in position 2806: illegal multibyte sequence
```

**Comment by wsdjeg** [comment]
Thanks for your work. :)
