### ISSUE TITLE
vimdoc.error.InconsistentControl: Inconsistent control "namespace"

### ISSUE THREAD

**Issue by wsdjeg** [google/vimdoc#106]
In windows 7, when run `python -m vimdoc .` in the root of my repo, I get following errors, I have updated vimdoc to the latest version:

```
C:\Users\Administrator\.SpaceVim>python -m vimdoc .
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\vimdoc\__main__.py", line 22, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\vimdoc\__main__.py", line 18, in main
    for module in Modules(args.plugin):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\vimdoc\module.py", line 467, in Modules
    main_module.Merge(block, namespace=namespace)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\vimdoc\module.py", line 50, in Merge
    block.Local(namespace=namespace)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\vimdoc\block.py", line 127, in Local
    raise error.InconsistentControl(key, self.locals[key], value)
vimdoc.error.InconsistentControl: Inconsistent control "namespace" (SpaceVim#api# vs SpaceVim\api#)
```

I am not sure if it is due to the difference between file sep in windows and *nix os.

**Comment by dbarnett** [comment]
Looks like an easy fix. Sent #107.

**Comment by wsdjeg** [comment]
@dbarnett Thanks, It works well for me, I just test it locally.
